language: node_js

install:
   - npm install

script: echo OK

deploy:
  provider: lambda
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  function_name: test_function_4
  region: us-east-1
  handler_name: myHandler
  runtime: nodejs4.3
  publish: true 
  #zip: index.js
  zip: deploy.zip
  role: $ROLE
  on:
    all_branches: true

before_deploy:
   - zip -r deploy.zip index.js package.json node_modules/

after_deploy:
   - unzip -l deploy.zip 
