language: node_js

script: echo OK

deploy:
  provider: lambda
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  function_name: test_function_4
  region: us-east-1
  handler_name: myHandler
  runtime: nodejs4.3
  publish: true 
  zip: index.js node_modules
  role: arn:aws:iam::710516728004:role/lambda_basic_execution
  on:
    all_branches: true
