language: node_js

script: echo OK

deploy:
  provider: lambda
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  function_name: test_function_3
  region: eu-central-1
  handler_name: myHandler
  zip: index.js
  role: arn:aws:iam::148075341626:role/LambdaBasicExecutor
  edge:
    source: vvondra/dpl
    branch: update_lambda_provider
  on:
    all_branches: true